branch-defaults:
  dev:
    environment: image-filter-starter-code-dev7
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  image-filter-starter-code-dev7:
    branch: null
    repository: null
global:
  application_name: image-filter-starter-code
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
